
# Role and binding needed for configurable max shares feature
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gcp-filestore-csi-role
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch"]

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gcp-filestore-csi-binding
subjects:
  - kind: ServiceAccount
    name: gcp-filestore-csi-controller-sa
    namespace: gcp-filestore-csi-driver
roleRef:
  kind: ClusterRole
  name: gcp-filestore-csi-role
  apiGroup: rbac.authorization.k8s.io

