apiVersion: apps/v1
kind: Deployment
metadata:
  name: filestorecsi-validation-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: filestorecsi-validation
  template:
    metadata:
      labels:
        app: filestorecsi-validation
    spec:
      serviceAccount: gcp-filestore-csi-webhook-sa
      containers:
      - name: filestorecsi-validation
        image: gcr.io/k8s-staging-cloud-provider-gcp/gcp-filestore-csi-driver-webhook
        imagePullPolicy: Always
        args: ['--tls-cert-file=/etc/filestorecsi-validation-webhook/certs/cert.pem', '--tls-private-key-file=/etc/filestorecsi-validation-webhook/certs/key.pem', '--feature-max-shares-per-instance=true']
        ports:
        - containerPort: 443 # change the port as needed
        volumeMounts:
          - name: filestorecsi-validation-webhook-certs
            mountPath: /etc/filestorecsi-validation-webhook/certs
            readOnly: true
      volumes:
        - name: filestorecsi-validation-webhook-certs
          secret:
            secretName: filestorecsi-validation-secret
---
apiVersion: v1
kind: Service
metadata:
  name: fs-validation
  namespace: default
spec:
  selector:
    app: filestorecsi-validation
  ports:
    - protocol: TCP
      port: 443 # Change if needed
      targetPort: 443 # Change if the webserver image expects a different port
