kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: preprov-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: my-pre-pv
  resources:
    requests:
      storage: 1Ti
