/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1alpha1 "sigs.k8s.io/gcp-filestore-csi-driver/pkg/apis/multishare/v1alpha1"
	scheme "sigs.k8s.io/gcp-filestore-csi-driver/pkg/client/clientset/versioned/scheme"
)

// InstanceInfosGetter has a method to return a InstanceInfoInterface.
// A group's client should implement this interface.
type InstanceInfosGetter interface {
	InstanceInfos() InstanceInfoInterface
}

// InstanceInfoInterface has methods to work with InstanceInfo resources.
type InstanceInfoInterface interface {
	Create(ctx context.Context, instanceInfo *v1alpha1.InstanceInfo, opts v1.CreateOptions) (*v1alpha1.InstanceInfo, error)
	Update(ctx context.Context, instanceInfo *v1alpha1.InstanceInfo, opts v1.UpdateOptions) (*v1alpha1.InstanceInfo, error)
	UpdateStatus(ctx context.Context, instanceInfo *v1alpha1.InstanceInfo, opts v1.UpdateOptions) (*v1alpha1.InstanceInfo, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.InstanceInfo, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.InstanceInfoList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.InstanceInfo, err error)
	InstanceInfoExpansion
}

// instanceInfos implements InstanceInfoInterface
type instanceInfos struct {
	client rest.Interface
}

// newInstanceInfos returns a InstanceInfos
func newInstanceInfos(c *MultishareV1alpha1Client) *instanceInfos {
	return &instanceInfos{
		client: c.RESTClient(),
	}
}

// Get takes name of the instanceInfo, and returns the corresponding instanceInfo object, and an error if there is any.
func (c *instanceInfos) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.InstanceInfo, err error) {
	result = &v1alpha1.InstanceInfo{}
	err = c.client.Get().
		Resource("instanceinfos").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of InstanceInfos that match those selectors.
func (c *instanceInfos) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.InstanceInfoList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.InstanceInfoList{}
	err = c.client.Get().
		Resource("instanceinfos").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested instanceInfos.
func (c *instanceInfos) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("instanceinfos").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a instanceInfo and creates it.  Returns the server's representation of the instanceInfo, and an error, if there is any.
func (c *instanceInfos) Create(ctx context.Context, instanceInfo *v1alpha1.InstanceInfo, opts v1.CreateOptions) (result *v1alpha1.InstanceInfo, err error) {
	result = &v1alpha1.InstanceInfo{}
	err = c.client.Post().
		Resource("instanceinfos").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(instanceInfo).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a instanceInfo and updates it. Returns the server's representation of the instanceInfo, and an error, if there is any.
func (c *instanceInfos) Update(ctx context.Context, instanceInfo *v1alpha1.InstanceInfo, opts v1.UpdateOptions) (result *v1alpha1.InstanceInfo, err error) {
	result = &v1alpha1.InstanceInfo{}
	err = c.client.Put().
		Resource("instanceinfos").
		Name(instanceInfo.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(instanceInfo).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *instanceInfos) UpdateStatus(ctx context.Context, instanceInfo *v1alpha1.InstanceInfo, opts v1.UpdateOptions) (result *v1alpha1.InstanceInfo, err error) {
	result = &v1alpha1.InstanceInfo{}
	err = c.client.Put().
		Resource("instanceinfos").
		Name(instanceInfo.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(instanceInfo).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the instanceInfo and deletes it. Returns an error if one occurs.
func (c *instanceInfos) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("instanceinfos").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *instanceInfos) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("instanceinfos").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched instanceInfo.
func (c *instanceInfos) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.InstanceInfo, err error) {
	result = &v1alpha1.InstanceInfo{}
	err = c.client.Patch(pt).
		Resource("instanceinfos").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
