/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "sigs.k8s.io/gcp-filestore-csi-driver/pkg/apis/lockrelease/v1alpha1"
)

// FakeLockInfos implements LockInfoInterface
type FakeLockInfos struct {
	Fake *FakeFilestoreV1alpha1
	ns   string
}

var lockinfosResource = v1alpha1.SchemeGroupVersion.WithResource("lockinfos")

var lockinfosKind = v1alpha1.SchemeGroupVersion.WithKind("LockInfo")

// Get takes name of the lockInfo, and returns the corresponding lockInfo object, and an error if there is any.
func (c *FakeLockInfos) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.LockInfo, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(lockinfosResource, c.ns, name), &v1alpha1.LockInfo{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.LockInfo), err
}

// List takes label and field selectors, and returns the list of LockInfos that match those selectors.
func (c *FakeLockInfos) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.LockInfoList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(lockinfosResource, lockinfosKind, c.ns, opts), &v1alpha1.LockInfoList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.LockInfoList{ListMeta: obj.(*v1alpha1.LockInfoList).ListMeta}
	for _, item := range obj.(*v1alpha1.LockInfoList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested lockInfos.
func (c *FakeLockInfos) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(lockinfosResource, c.ns, opts))

}

// Create takes the representation of a lockInfo and creates it.  Returns the server's representation of the lockInfo, and an error, if there is any.
func (c *FakeLockInfos) Create(ctx context.Context, lockInfo *v1alpha1.LockInfo, opts v1.CreateOptions) (result *v1alpha1.LockInfo, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(lockinfosResource, c.ns, lockInfo), &v1alpha1.LockInfo{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.LockInfo), err
}

// Update takes the representation of a lockInfo and updates it. Returns the server's representation of the lockInfo, and an error, if there is any.
func (c *FakeLockInfos) Update(ctx context.Context, lockInfo *v1alpha1.LockInfo, opts v1.UpdateOptions) (result *v1alpha1.LockInfo, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(lockinfosResource, c.ns, lockInfo), &v1alpha1.LockInfo{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.LockInfo), err
}

// Delete takes name of the lockInfo and deletes it. Returns an error if one occurs.
func (c *FakeLockInfos) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(lockinfosResource, c.ns, name, opts), &v1alpha1.LockInfo{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeLockInfos) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(lockinfosResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.LockInfoList{})
	return err
}

// Patch applies the patch and returns the patched lockInfo.
func (c *FakeLockInfos) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.LockInfo, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(lockinfosResource, c.ns, name, pt, data, subresources...), &v1alpha1.LockInfo{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.LockInfo), err
}
