/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	multisharev1alpha1 "sigs.k8s.io/gcp-filestore-csi-driver/pkg/apis/multishare/v1alpha1"
	versioned "sigs.k8s.io/gcp-filestore-csi-driver/pkg/client/clientset/versioned"
	internalinterfaces "sigs.k8s.io/gcp-filestore-csi-driver/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "sigs.k8s.io/gcp-filestore-csi-driver/pkg/client/listers/multishare/v1alpha1"
)

// InstanceInfoInformer provides access to a shared informer and lister for
// InstanceInfos.
type InstanceInfoInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.InstanceInfoLister
}

type instanceInfoInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewInstanceInfoInformer constructs a new informer for InstanceInfo type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewInstanceInfoInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredInstanceInfoInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredInstanceInfoInformer constructs a new informer for InstanceInfo type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredInstanceInfoInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.MultishareV1alpha1().InstanceInfos().List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.MultishareV1alpha1().InstanceInfos().Watch(context.TODO(), options)
			},
		},
		&multisharev1alpha1.InstanceInfo{},
		resyncPeriod,
		indexers,
	)
}

func (f *instanceInfoInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredInstanceInfoInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *instanceInfoInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&multisharev1alpha1.InstanceInfo{}, f.defaultInformer)
}

func (f *instanceInfoInformer) Lister() v1alpha1.InstanceInfoLister {
	return v1alpha1.NewInstanceInfoLister(f.Informer().GetIndexer())
}
