apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pre-pv
  annotations:
    pv.kubernetes.io/provisioned-by: filestore.csi.storage.gke.io
spec:
  storageClassName: ""
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  csi:
    driver: filestore.csi.storage.gke.io
    # Modify this to use the zone, filestore instance and share name.
    volumeHandle: "modeInstance/<zone>/<filestore-instance-name>/<filestore-share-name>"
    volumeAttributes:
      ip: <Filestore Instance IP> # Modify this to Pre-provisioned Filestore instance IP
      volume: <Filestore Share Name> # Modify this to Pre-provisioned Filestore instance share name
