/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	"time"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1 "sigs.k8s.io/gcp-filestore-csi-driver/pkg/apis/multishare/v1"
	scheme "sigs.k8s.io/gcp-filestore-csi-driver/pkg/client/clientset/versioned/scheme"
)

// ShareInfosGetter has a method to return a ShareInfoInterface.
// A group's client should implement this interface.
type ShareInfosGetter interface {
	ShareInfos(namespace string) ShareInfoInterface
}

// ShareInfoInterface has methods to work with ShareInfo resources.
type ShareInfoInterface interface {
	Create(ctx context.Context, shareInfo *v1.ShareInfo, opts metav1.CreateOptions) (*v1.ShareInfo, error)
	Update(ctx context.Context, shareInfo *v1.ShareInfo, opts metav1.UpdateOptions) (*v1.ShareInfo, error)
	UpdateStatus(ctx context.Context, shareInfo *v1.ShareInfo, opts metav1.UpdateOptions) (*v1.ShareInfo, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.ShareInfo, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.ShareInfoList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.ShareInfo, err error)
	ShareInfoExpansion
}

// shareInfos implements ShareInfoInterface
type shareInfos struct {
	client rest.Interface
	ns     string
}

// newShareInfos returns a ShareInfos
func newShareInfos(c *MultishareV1Client, namespace string) *shareInfos {
	return &shareInfos{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the shareInfo, and returns the corresponding shareInfo object, and an error if there is any.
func (c *shareInfos) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.ShareInfo, err error) {
	result = &v1.ShareInfo{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("shareinfos").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ShareInfos that match those selectors.
func (c *shareInfos) List(ctx context.Context, opts metav1.ListOptions) (result *v1.ShareInfoList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.ShareInfoList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("shareinfos").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested shareInfos.
func (c *shareInfos) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("shareinfos").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a shareInfo and creates it.  Returns the server's representation of the shareInfo, and an error, if there is any.
func (c *shareInfos) Create(ctx context.Context, shareInfo *v1.ShareInfo, opts metav1.CreateOptions) (result *v1.ShareInfo, err error) {
	result = &v1.ShareInfo{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("shareinfos").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(shareInfo).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a shareInfo and updates it. Returns the server's representation of the shareInfo, and an error, if there is any.
func (c *shareInfos) Update(ctx context.Context, shareInfo *v1.ShareInfo, opts metav1.UpdateOptions) (result *v1.ShareInfo, err error) {
	result = &v1.ShareInfo{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("shareinfos").
		Name(shareInfo.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(shareInfo).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *shareInfos) UpdateStatus(ctx context.Context, shareInfo *v1.ShareInfo, opts metav1.UpdateOptions) (result *v1.ShareInfo, err error) {
	result = &v1.ShareInfo{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("shareinfos").
		Name(shareInfo.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(shareInfo).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the shareInfo and deletes it. Returns an error if one occurs.
func (c *shareInfos) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("shareinfos").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *shareInfos) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("shareinfos").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched shareInfo.
func (c *shareInfos) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.ShareInfo, err error) {
	result = &v1.ShareInfo{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("shareinfos").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
