apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volumepool-pvc
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: staging-volume-pool-sc
  resources:
    requests:
      storage: 10Gi
