/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "sigs.k8s.io/gcp-filestore-csi-driver/pkg/apis/multishare/v1alpha1"
)

// FakeInstanceInfos implements InstanceInfoInterface
type FakeInstanceInfos struct {
	Fake *FakeMultishareV1alpha1
}

var instanceinfosResource = schema.GroupVersionResource{Group: "multishare.filestore.csi.storage.gke.io", Version: "v1alpha1", Resource: "instanceinfos"}

var instanceinfosKind = schema.GroupVersionKind{Group: "multishare.filestore.csi.storage.gke.io", Version: "v1alpha1", Kind: "InstanceInfo"}

// Get takes name of the instanceInfo, and returns the corresponding instanceInfo object, and an error if there is any.
func (c *FakeInstanceInfos) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.InstanceInfo, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(instanceinfosResource, name), &v1alpha1.InstanceInfo{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.InstanceInfo), err
}

// List takes label and field selectors, and returns the list of InstanceInfos that match those selectors.
func (c *FakeInstanceInfos) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.InstanceInfoList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(instanceinfosResource, instanceinfosKind, opts), &v1alpha1.InstanceInfoList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.InstanceInfoList{ListMeta: obj.(*v1alpha1.InstanceInfoList).ListMeta}
	for _, item := range obj.(*v1alpha1.InstanceInfoList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested instanceInfos.
func (c *FakeInstanceInfos) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(instanceinfosResource, opts))
}

// Create takes the representation of a instanceInfo and creates it.  Returns the server's representation of the instanceInfo, and an error, if there is any.
func (c *FakeInstanceInfos) Create(ctx context.Context, instanceInfo *v1alpha1.InstanceInfo, opts v1.CreateOptions) (result *v1alpha1.InstanceInfo, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(instanceinfosResource, instanceInfo), &v1alpha1.InstanceInfo{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.InstanceInfo), err
}

// Update takes the representation of a instanceInfo and updates it. Returns the server's representation of the instanceInfo, and an error, if there is any.
func (c *FakeInstanceInfos) Update(ctx context.Context, instanceInfo *v1alpha1.InstanceInfo, opts v1.UpdateOptions) (result *v1alpha1.InstanceInfo, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(instanceinfosResource, instanceInfo), &v1alpha1.InstanceInfo{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.InstanceInfo), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeInstanceInfos) UpdateStatus(ctx context.Context, instanceInfo *v1alpha1.InstanceInfo, opts v1.UpdateOptions) (*v1alpha1.InstanceInfo, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(instanceinfosResource, "status", instanceInfo), &v1alpha1.InstanceInfo{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.InstanceInfo), err
}

// Delete takes name of the instanceInfo and deletes it. Returns an error if one occurs.
func (c *FakeInstanceInfos) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(instanceinfosResource, name, opts), &v1alpha1.InstanceInfo{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeInstanceInfos) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(instanceinfosResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.InstanceInfoList{})
	return err
}

// Patch applies the patch and returns the patched instanceInfo.
func (c *FakeInstanceInfos) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.InstanceInfo, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(instanceinfosResource, name, pt, data, subresources...), &v1alpha1.InstanceInfo{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.InstanceInfo), err
}
