__title__ = "pyNfsClient"
__description__ = "Pure python NFS client"
__version__ = "0.1.5"
__license__ = "MIT"
__url__ = "https://github.com/CharmingYang0/NfsClient"
__author__ = "Cooper Yang"
__author_email__ = "cm_yang@yeah.net"
